<?php
/**
 * Implement hook_modules_enabled().
 * Typically, defaultcontent.module waits for cron to create nodes.
 * This forces node creation immediately, then sets front page URL.
 */
function datagov_base_extra_modules_enabled($modules) {   
  // quit if datagov_base hasn't been enabled
  if (!in_array('datagov_base', $modules)) return;

  /*$result = db_insert('menu_links')
    ->fields(array(
      'menu_name' => 'user-menu',
      'plid' => '0',
      'link_path' => 'user/login',
      'router_path' => 'user/login',
      'link_title' => 'Log in',
      'module' => 'menu',
      'hidden' => '0',
      'depth' => '1',
      'customized' => '1',
    ))
    ->execute();*/

  // insert log in menu link into user-menu
  $item = array(
    'menu_name' => 'user-menu',
    'module' => 'menu',
    'router_path' => 'user/login',
    'link_path' => 'user/login',
    'link_title' => 'Log in',
  );
  menu_link_save($item);
}
