<?php
/**
 * Implement hook_modules_enabled().
 * Typically, defaultcontent.module waits for cron to create nodes.
 * This forces node creation immediately, then sets front page URL.
 */
function datagov_base_extra_modules_enabled($modules) {   
  // quit if datagov_base hasn't been enabled
  if (!in_array('datagov_base', $modules)) return;

  // insert log in menu link into user-menu
  $item = array(
    'menu_name' => 'user-menu',
    'module' => 'menu',
    'router_path' => 'user/login',
    'link_path' => 'user/login',
    'link_title' => 'Log in',
  );
  menu_link_save($item);

  // set user-menu block title to <none>
  db_merge('block')
    ->key(array(
      'theme' => 'datagov',
      'module' => 'system',
      'delta' => 'user-menu',
    ))
    ->fields(array(
      'status' => 0,
      'weight' => 0,
      'region' => -1,
      'custom' => 0,
      'visibility' => 0,
      'pages' => '',
      'title' => '<none>',
      'cache' => -1,
    ))
    ->execute();

  // set main-menu block title to <none>
  db_merge('block')
    ->key(array(
      'theme' => 'datagov',
      'module' => 'superfish',
      'delta' => '1',
    ))
    ->fields(array(
      'status' => 0,
      'weight' => 0,
      'region' => -1,
      'custom' => 0,
      'visibility' => 0,
      'pages' => '',
      'title' => '<none>',
      'cache' => -1,
    ))
    ->execute();
}
