$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'text_resize__0',
  'skin' => 'fusion_apply_settings__block_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-block-group-datagov-groups-fusion-layout',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'text_resize__0',
  'skin' => 'fusion_skins_block_positioning',
  'options' => 
  array (
    0 => 'fusion-right',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'text_resize__0',
  'skin' => 'fusion_skins_grid12_width',
  'options' => 
  array (
    0 => 'grid12-2',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'text_resize__0',
  'skin' => 'fusion_skins_grid16_width',
  'options' => 
  array (
    0 => 'grid16-2',
  ),
  'status' => '0',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'menu__menu-footer-menu',
  'skin' => 'fusion_apply_settings__block_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-block-group-datagov-groups-additional',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'menu__menu-footer-menu',
  'skin' => 'fusion_skins_block_positioning',
  'options' => 
  array (
    0 => 'fusion-center',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'menu__menu-footer-menu',
  'skin' => 'fusion_menu',
  'options' => 
  array (
    0 => 'fusion-inline-menu',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'search__form',
  'skin' => 'fusion_apply_settings__block_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-block-group-datagov-groups-fusion-layout',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'search__form',
  'skin' => 'fusion_skins_grid12_width',
  'options' => 
  array (
    0 => 'grid12-6',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'blockify__blockify-logo',
  'skin' => 'fusion_apply_settings__block_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-block-group-datagov-groups-fusion-layout',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'blockify__blockify-logo',
  'skin' => 'fusion_skins_grid12_width',
  'options' => 
  array (
    0 => 'grid12-6',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'search__form',
  'skin' => 'fusion_skins_content_alignment',
  'options' => 
  array (
    0 => 'fusion-center',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'menu__menu-footer-menu',
  'skin' => 'fusion_skins_content_alignment',
  'options' => 
  array (
    0 => 'fusion-right',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'superfish__1',
  'skin' => 'fusion_apply_settings__block_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-block-group-datagov-groups-menus',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'superfish__1',
  'skin' => 'fusion_skins_grid12_width',
  'options' => 
  array (
    0 => 'grid12-12',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'boxes__usaflag_info',
  'skin' => '_additional',
  'options' => 
  array (
    0 => 'usaflag-info',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'boxes__usaflag_info',
  'skin' => 'fusion_apply_settings__block_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-block-group-datagov-groups-general',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'boxes__usaflag_info',
  'skin' => 'fusion_skins_grid12_width',
  'options' => 
  array (
    0 => 'grid12-4',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'text_resize__0',
  'skin' => '_additional',
  'options' => 
  array (
    0 => 'textresize-block',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'search__form',
  'skin' => '_additional',
  'options' => 
  array (
    0 => 'search-block-form',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'system__main',
  'skin' => 'fusion_apply_settings__block_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-block-group-datagov-groups-fusion-layout',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'page_logo__page_logo',
  'skin' => 'fusion_apply_settings__block_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-block-group-datagov-groups-layout',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'page_logo__page_logo',
  'skin' => 'fusion_skins_grid12_width',
  'options' => 
  array (
    0 => 'grid12-3',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'views__slideshow-block',
  'skin' => 'fusion_apply_settings__block_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-block-group-datagov-groups-fusion-layout',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'views__slideshow-block',
  'skin' => 'fusion_skins_grid12_width',
  'options' => 
  array (
    0 => 'grid12-9',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'page_logo__page_logo',
  'skin' => 'fusion_skins_content_alignment',
  'options' => 
  array (
    0 => 'fusion-center',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'boxes__current_date_preheader',
  'skin' => 'fusion_apply_settings__block_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-block-group-datagov-groups-layout',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'boxes__current_date_preheader',
  'skin' => 'fusion_skins_grid12_width',
  'options' => 
  array (
    0 => 'grid12-2',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'boxes__current_date_preheader',
  'skin' => '_additional',
  'options' => 
  array (
    0 => 'current-date-preheader',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'boxes__current_date_preheader',
  'skin' => 'fusion_skins_block_positioning',
  'options' => 
  array (
    0 => 'fusion-right',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'boxes__datagov_footer_logo',
  'skin' => 'fusion_apply_settings__block_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-block-group-datagov-groups-additional',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'boxes__datagov_footer_logo',
  'skin' => 'fusion_skins_content_alignment',
  'options' => 
  array (
    0 => 'fusion-right',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'boxes__datagov_footer_logo',
  'skin' => 'fusion_skins_grid12_width',
  'options' => 
  array (
    0 => 'grid12-12',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'boxes__datagov_footer_logo',
  'skin' => '_additional',
  'options' => 
  array (
    0 => 'datagov-footer-logo',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'menu__menu-footer-menu',
  'skin' => '_additional',
  'options' => 
  array (
    0 => 'footer-menu',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'text_resize__0',
  'skin' => 'fusion_equal_heights',
  'options' => 
  array (
    'equal-heights' => 'equal-heights',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'blockify__blockify-logo',
  'skin' => '_additional',
  'options' => 
  array (
    0 => 'logo',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'text_resize__0',
  'skin' => 'fusion_skins_content_alignment',
  'options' => 
  array (
    0 => 'fusion-right',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'boxes__current_date_preheader',
  'skin' => 'fusion_skins_content_alignment',
  'options' => 
  array (
    0 => 'fusion-right',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'addthis__addthis_block',
  'skin' => '_additional',
  'options' => 
  array (
    0 => 'addthis-block',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'addthis__addthis_block',
  'skin' => 'fusion_apply_settings__block_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-block-group-datagov-groups-layout',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'addthis__addthis_block',
  'skin' => 'fusion_skins_block_positioning',
  'options' => 
  array (
    0 => 'fusion-right',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'superfish__1',
  'skin' => 'fusion_menu',
  'options' => 
  array (
    0 => 'fusion-multicol-menu',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'boxes__home_latest_datasets',
  'skin' => '_additional',
  'options' => 
  array (
    0 => 'home-latest-datasets',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'boxes__home_latest_datasets',
  'skin' => 'fusion_apply_settings__block_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-block-group-datagov-groups-additional',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'panels',
  'element' => 'pane__1__9',
  'skin' => '_additional',
  'options' => 
  array (
    0 => 'home-latest-datasets',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'panels',
  'element' => 'pane__1__9',
  'skin' => 'fusion_apply_settings__panels_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-panels-group-datagov-groups-additional',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'panels',
  'element' => 'pane__9__22',
  'skin' => '_additional',
  'options' => 
  array (
    0 => 'home-latest-datasets',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'panels',
  'element' => 'pane__9__22',
  'skin' => 'fusion_apply_settings__panels_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-panels-group-datagov-groups-additional',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'panels',
  'element' => 'pane__12__27',
  'skin' => 'fusion_apply_settings__panels_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-panels-group-datagov-groups-additional',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'boxes__whatsnew_in_the_news',
  'skin' => 'fusion_apply_settings__block_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-block-group-datagov-groups-additional',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'boxes__whatsnew_in_the_news',
  'skin' => '_additional',
  'options' => 
  array (
    0 => 'whats-new-feature-box',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'boxes__whatsnew_newest_datasets',
  'skin' => 'fusion_apply_settings__block_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-block-group-datagov-groups-additional',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'boxes__whatsnew_newest_datasets',
  'skin' => '_additional',
  'options' => 
  array (
    0 => 'whats-new-feature-box',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'boxes__whatsnew_new_features',
  'skin' => 'fusion_apply_settings__block_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-block-group-datagov-groups-additional',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'boxes__whatsnew_new_features',
  'skin' => '_additional',
  'options' => 
  array (
    0 => 'whats-new-feature-box',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'node',
  'element' => 'panel',
  'skin' => 'fusion_apply_settings__node_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-node-group-datagov-groups-layout',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'panels',
  'element' => 'pane__2__13',
  'skin' => 'fusion_apply_settings__panels_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-panels-group-datagov-groups-additional',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'panels',
  'element' => 'pane__2__13',
  'skin' => '_additional',
  'options' => 
  array (
    0 => 'whats-new-feature-box',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'panels',
  'element' => 'pane__2__15',
  'skin' => 'fusion_apply_settings__panels_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-panels-group-datagov-groups-additional',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'panels',
  'element' => 'pane__2__15',
  'skin' => '_additional',
  'options' => 
  array (
    0 => 'whats-new-additional-information',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'panels',
  'element' => 'pane__5__37',
  'skin' => '_additional',
  'options' => 
  array (
    0 => 'whats-new-additional-information',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'panels',
  'element' => 'pane__5__37',
  'skin' => 'fusion_apply_settings__panels_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-panels-group-datagov-groups-additional',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'views__latest_datasets-block',
  'skin' => '_additional',
  'options' => 
  array (
    0 => 'home-latest-datasets',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'views__latest_datasets-block',
  'skin' => 'fusion_apply_settings__block_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-block-group-datagov-groups-additional',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'panels',
  'element' => 'pane__5__61',
  'skin' => '_additional',
  'options' => 
  array (
    0 => 'whats-new-feature-box',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'panels',
  'element' => 'pane__5__61',
  'skin' => 'fusion_apply_settings__panels_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-panels-group-datagov-groups-additional',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'og_menu__og_single_menu_block',
  'skin' => '_additional',
  'options' => 
  array (
    0 => 'comCatMenu',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'og_menu__og_single_menu_block',
  'skin' => 'fusion_apply_settings__block_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-block-group-datagov-groups-additional',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'system__user-menu',
  'skin' => 'fusion_apply_settings__block_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-block-group-datagov-groups-fusion-layout',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'system__user-menu',
  'skin' => 'fusion_skins_grid12_width',
  'options' => 
  array (
    0 => 'grid12-6',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'block',
  'element' => 'system__user-menu',
  'skin' => 'fusion_skins_content_alignment',
  'options' => 
  array (
    0 => 'fusion-center',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'node',
  'element' => 'page',
  'skin' => 'fusion_apply_settings__node_group__datagov__groups__active_tab',
  'options' => 
  array (
    0 => 'edit-fusion-apply-settings-node-group-datagov-groups-additional',
  ),
  'status' => '1',
);
$skins[] = array (
  'theme' => 'datagov',
  'module' => 'node',
  'element' => 'page',
  'skin' => 'fusion_skins_content_alignment',
  'options' => 
  array (
    0 => 'fusion-center',
  ),
  'status' => '1',
);
